package com.elangzhi.ssm.model;

public class Label extends BaseModel{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_label.id
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_label.name
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_label.type
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_label.intro
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_label.status
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_label
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    public Label(Long id, String name, Integer type, String intro, Integer status) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.intro = intro;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_label
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    public Label() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_label.id
     *
     * @return the value of t_label.id
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_label.id
     *
     * @param id the value for t_label.id
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_label.name
     *
     * @return the value of t_label.name
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_label.name
     *
     * @param name the value for t_label.name
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_label.type
     *
     * @return the value of t_label.type
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_label.type
     *
     * @param type the value for t_label.type
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_label.intro
     *
     * @return the value of t_label.intro
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_label.intro
     *
     * @param intro the value for t_label.intro
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_label.status
     *
     * @return the value of t_label.status
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_label.status
     *
     * @param status the value for t_label.status
     *
     * @mbggenerated Sat May 21 00:16:41 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}